### ISSUE TITLE
Mimetype detection

### ISSUE THREAD

**Issue by Boltovnya** [empyreanfs/Empyrean#2]
So I was uploading a python script with file extension `.py` and well, it detected as `.exe`.
Here's a paste of what happened:
`addons ツ empyrean media_spam_mpchc.py`
`----Uploading media_spam_mpchc.py`
`----https://serve.empy.org/AyR8qmGB8X.exe`

The same happens with paste.empy.org, here:
![wtf](https://serve.empy.org/Lx7XKJhXl9.png)

Oh btw, here's the link to the actual file: http://hastebin.com/umukehaxus.tfwno.gf

**Comment by NinjaTomate** [comment]
Can reproduce with linked file; other .py files correctly upload as plaintext.

**Comment by Bob131** [comment]
The python-magic library depends on having libmagic configured correctly with a sane /etc/magic file. Unfortunately, CentOS's file-libs package does not provide a sensible magic file, so mimetype detection is pretty poor. Deployment on a more desktop-oriented distro, such as Ubuntu Server or Fedora Server would be much more ideal, but that either requires more money or for me to migrate all of my VPS's operations to a new machine.

Aside from hard-coding in heuristics which are meant to already exist in /etc/magic, there's not much we can do in Empyrean-core to mitigate this. Sorry
